//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenelMenu
    {
        public GenelMenu()
        {
            this.Menu = new HashSet<Menu>();
        }
    
        public int MenuId { get; set; }
        public string Genelad { get; set; }
    
        public virtual ICollection<Menu> Menu { get; set; }
    }
}
