//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Masa
    {
        public Masa()
        {
            this.Siparis = new HashSet<Siparis>();
        }
    
        public int MasaId { get; set; }
        public string MasaAdi { get; set; }
        public int aktif { get; set; }
    
        public virtual ICollection<Siparis> Siparis { get; set; }
    }
}
