//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SiparisKontrolEntities : DbContext
    {
        public SiparisKontrolEntities()
            : base("name=SiparisKontrolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GenelMenu> GenelMenu { get; set; }
        public virtual DbSet<Masa> Masa { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Mesaj> Mesaj { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<Siparis> Siparis { get; set; }
        public virtual DbSet<siparismenü> siparismenü { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
